id: PC33F0E42
initial_creation_type: ocr
source_metadata:
  volumes:
    99b88902078a475580ca0a093a4ac97a:
      base_file: v105.txt
      image_group_id: I1PD95950
      title: རིགས་པའི་ཐིགས་པའི་ཕྱོགས་སྔ་མ་མདོར་བསྡུས་པ།
      total_pages: 910
      volume_number: 105
